/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Project, Profile } from './types';

export const INITIAL_PROFILE: Profile = {
  name: 'Admin Profile',
  role: 'Director Mode',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8dUjd5LmoT6EEa6tRNrhv9V7tUH5uAHyIDvw57nvZP6oa2L6FAF13WWtctu9RdVCdRrM4ev2JbW2dggmB-EkWAcBX5hWKVmBynvdKTHdHNvPxGC_Q51VNguBPF_wlE6LBMS2ML7ARrTjaGFMmnqhUn7wDfOZl76mhnzjBI4TlY-snlPmjZOaNZU87Q03naCnFbf1zSrVnZt7k3B8mhs5HAohNETG1MYS8ziOKrgLUSg8q4difcrvoLQan866PUsPR7oNFjAwnQv4',
  tagline: 'Architect of Digital Experiences',
  bio: 'I bridge the gap between architectural precision and digital fluidity, creating high-fidelity interfaces for global visionaries and top-tier engineering teams.',
  email: 'hello@studiopro.design',
  mode: 'director'
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'The Glass Pavilion',
    description: 'Redefining spatial boundaries through transparency and modular structural engineering. A study in light and atmosphere in a serene, foggy forest at dawn.',
    category: 'Architecture',
    tags: 'Architecture, 3D Modeling, Glass, Sustainable',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpFZ7y23Eemp5uGwLWpP-YUcdCfrqNSZkbmyUKrbSMyN8Y14-h3esD_yk1NSyAvtrXgTv-HUHxhkOkHyoM5EGQa4SoOFBc_4-mtMbjzIlkrN94fUWTtBBFUiXHVzeyWgAqc4-XVEcRG5REUUmtYyno865_jQFGwjPo4EzkmpyiJHLJjCBeocCFDAIvcAncU7SbrXpBDhNGo7SfOXTxRrTs9N1Y0ZZEgyRZsavu-1TptW86vzr5lPFEBeKmMwbZy67TPCTh0JIzE8Q',
    views: 1450,
    viewsGrowth: 15.6,
    modifiedAt: 'Just now',
    createdAtDate: 'Mar 15, 2024',
    client: 'Private Owner',
    year: 2024,
    status: 'Published',
    location: 'Seattle, WA',
    featured: true
  },
  {
    id: 'proj-2',
    title: 'Nexus Dashboard',
    description: 'Close-up high-fidelity design of a sleek, dark metallic user interface dashboard for an advanced data analytics platform with neon accents.',
    category: 'UI/UX',
    tags: 'Product Design, UI/UX, Dark Mode, Interactive',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB_4DyJAFMh_3Z5Zbq9I0SMYddQ-GCRBdcYS6i4mdofRtYO13tQJTeiNIw1KIVt_rrH61HwNI9tSXGKNvBwivuGt3gqYYTlwFNjPNa2wIGl6flyUzFDv-oXog-GDENwyHTOL6zYkmig1Q-fLRzOp0pxTV28UU-arxP9OYR-oqyvgYHdpho2jOUGzMUuJhbm4CNtMY6cp7IRvoJhbLWh_GaNAyj9Ysta6F4rWO_BQkqz-OBeSLFiRG62nBL4jpr0YjtIDGdCUUmuJOo',
    views: 1029,
    viewsGrowth: 5.1,
    modifiedAt: '1 day ago',
    createdAtDate: 'Nov 04, 2023',
    client: 'Commercial',
    year: 2024,
    status: 'Published',
    location: 'Tokyo',
    featured: true
  },
  {
    id: 'proj-3',
    title: 'Monolith Identity',
    description: 'An abstract 3D composition of interlocking geometric shapes in a monochrome palette with deep navy accents. Built with brushed aluminum and matte ceramic finishes.',
    category: 'Visual Branding',
    tags: 'Branding, 3D, Abstract, CGI',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDFImFPAYwpPtpE0FETCiZbil_nJ3REVbOpvRq5XxBI2Axn0sXwl_28F8gcaiECjq6OFRb9jQp7NitdRrqInKPzl93z4MYmr2Z_TCFP2NrYhz8ZPTcOhcgpY2zOGbZctuar94GhJsVV2qmKJEReiPJ1J1Uw-Q5mX92BMJG1kcdE4vioGAtRIgEvyhTIxczWfvaajlp-d0laYP7GRuWQdLeOzOstWd32NZyfh_5UHp1M_Ge5A0psnLM5PX04uTX_MvnxwE2cH3GWJQI',
    views: 890,
    viewsGrowth: -1.2,
    modifiedAt: '3 days ago',
    createdAtDate: 'Feb 10, 2024',
    client: 'Monolith Corp',
    year: 2024,
    status: 'Published',
    location: 'New York',
    featured: true
  },
  {
    id: 'proj-4',
    title: 'Urban Transit Hub',
    description: 'A wide-angle cinematic concept of a modern city at twilight, focusing on a futuristic high-speed transit station with sweeping white curves and integrated gardens.',
    category: 'Architecture',
    tags: 'Smart City, Infrastructure, Concept, CGI',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBd3iR6UQxHoEIp2_m-utDApzkGTqHCg48pxSOlLDKqt7obkkx5iqhwYB0FGFGn7sO0HSDFTKv5Pp6MQKzBuVt9deBp5DTCuDG0VuwWBjO3NxH6B57CH4F9o79F7wUUut7nVjZbC5HuHLmnJjYLZhy7hzkVq_l3D5O-iUOm9SWTZL43btdKjIxo2jtL9EIT5dcyAfGSpfm6mFZmddFtuCEyhoznf1rdhvdqfV9LrztLgWdNHVhhR9vXA5qDmkIP7tmIR6Y8_IMlsXE',
    views: 2840,
    viewsGrowth: -2.3,
    modifiedAt: '4 days ago',
    createdAtDate: 'Dec 15, 2023',
    client: 'Municipal Transit Authority',
    year: 2023,
    status: 'Published',
    location: 'Singapore',
    featured: true
  },
  {
    id: 'proj-5',
    title: 'Modernist Retreat',
    description: 'A minimalist architectural visualization of a brutalist concrete museum in a desert landscape using stark midday sun and precise geometric shadows.',
    category: 'Architecture',
    tags: 'Architecture, Desert, Brutalist, Concrete',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0awIjG1_xNxNtHbTzv80jc0s-NdveUIstHjxXSHLnKObLDqrNNkH2Ccn7FePN1o-y0-kjnGcL8DKIArL4mxTOczPHv8SAQGafQ5RctF5nmloCqX39uPMWDLhSny4XvUrVi625O54nMxxY8pg3CrEkxtvajnFpEWHkHgYuzXVHVp_6CsgUyiSbOI3OAhb2RHFV5-uR8moa4P_h70DWzziszIONFuGixx4nUdH_AMXrwoQ1bwPq3z5XTvgmGAuMl1Lf8rGFFy8P7BQ',
    views: 432,
    viewsGrowth: 12.4,
    modifiedAt: '2 hours ago',
    createdAtDate: 'Jan 08, 2024',
    client: 'Retreat Co.',
    year: 2024,
    status: 'Published',
    location: 'Palm Springs',
    featured: true
  },
  {
    id: 'proj-6',
    title: 'Neo-Core Platform',
    description: 'A highly technological, electric blue accented dark user interface display showcasing deep analytics with beautiful neon visual telemetry.',
    category: 'UI/UX',
    tags: 'Digital Design, App, Fintech',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9crIMSlcd6FVT5mjD-67bPKEB6U1WmUr2skA0yBFpp7X-BSUIPXM0gpCEZ5THNuqj2BgxJjUgjnCRwTYfhYUA8mTGjcRmeYdBLUiWDDXrqUSlzMs_2Jw_xz4wy2bMydHItyuW8Z-EdzpxNhGsCgxJwL2C9R4OeK2mIYzLIQO31w5IZ57uUZwuCg4x_YIjT4tI0WFi-14wfAneWnz6XuWhHGVYtCrGJt3F_H3gyNfhx7hsMLj0ZCll1RoVShxAiVCI--JbKtpukEE',
    views: 1029,
    viewsGrowth: 5.1,
    modifiedAt: '1 day ago',
    createdAtDate: 'Feb 15, 2024',
    client: 'Neo Fintech',
    year: 2024,
    status: 'Published',
    location: 'San Francisco',
    featured: false
  },
  {
    id: 'proj-7',
    title: 'Vogue Editorial \'23',
    description: 'A high-fashion editorial photography project featuring sculptural avant-garde garments in a vast white warehouse with long, dramatic shadows.',
    category: 'Photography',
    tags: 'Creative Direction, Fashion, Black and White',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDse8sSK74k9WwBHMIW29jTj0MRfyE058rHuBkkaKrQ6cjrT5FLtWIK_OZ6Wc5ACcJPZzRG60KBFTHi-89bqg4IUc_WMonB8zyJZ0exEieuGgbbMTJfwvn-f8L0dXYl3hir26bCmtEcrbJUvEtURcYwky2xZREge-1U9FaxysbJ3-Z2y9D0Kyy85lNcj3G25I11gv8f-ML173VBeAADgF7ageyagzccstYmORmA1pfP1pP8V8qQwhjhKOM3PY8TwDDLRkGeGHsH0Ec',
    views: 2840,
    viewsGrowth: -2.3,
    modifiedAt: '4 days ago',
    createdAtDate: 'Dec 01, 2023',
    client: 'Vogue Magazine',
    year: 2023,
    status: 'Published',
    location: 'Paris, FR',
    featured: false
  },
  {
    id: 'proj-8',
    title: 'Brutalist Pavilion',
    description: 'A structural exploration of raw textured concrete forms intersecting against a pure blue atmosphere in an open-air public pavilion layout.',
    category: 'Architecture',
    tags: 'Brutalist, Raw Concrete, Modernist',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA_Jbtl9NkAhEL59izcEuvh7OLtfwp64slslyYrnQnnj5x9hNQSGIy3456i27Ehl8GmmWCeLdDIiHaOwlHr4wpgiuhtvdis2me9RJRMxX2GIvRMs-Ftmrlh4aBZllbvqawErWLS5iGlWD3pt58Y3zhjb7qtXAJt5BNn9lUW6vQ1ujAwUIOXhwi6wPSiJ62nqlziD-HS-fTI0WWLYf0UrSTb773ZY8fOfkRPGXLMGQ5hG3GwL3OZZYWDOC6sdowJfLNao_6mjCK2AqU',
    views: 1240,
    viewsGrowth: 8.9,
    modifiedAt: '6 days ago',
    createdAtDate: 'Oct 12, 2023',
    client: 'Public Space',
    year: 2023,
    status: 'Published',
    location: 'Berlin',
    featured: true
  },
  {
    id: 'proj-9',
    title: 'Azure Corporate Hub',
    description: 'A commercial tower architectural showcase reflecting amber sunsets on complex steel-framed triple-glazed high-efficiency glass curtain walls.',
    category: 'Design',
    tags: 'Corporate Office, Sustainable Glass, Structural',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCb_TfBsgLupRr-N0lqYWj7DJOHdTvCjW3xePNmlNQ4rl2upQnv8aXgeVVC_zteOp6vrs4FKWzBWEg3i8xzFdpB8dOcd8oh17sbTvVgKpdaKq24GflO0sZWK7t5qdnDmdmVZRRQ_Q1j22G5QjOjhClWv8x0LdiRfJsaH9KVjiXwtpFOOeC9Oe07OlzunExeO2pAPwRHoHbYAJYoOXmyZo2vZZDXjuz3FNFj7C8IwplRz2oukLP2aDbZ5VPCsaKtmV6-rknj0XzFBfY',
    views: 2043,
    viewsGrowth: 14.2,
    modifiedAt: '1 week ago',
    createdAtDate: 'Nov 04, 2023',
    client: 'Commercial',
    year: 2023,
    status: 'Published',
    location: 'Tokyo',
    featured: true
  },
  {
    id: 'proj-10',
    title: 'Nordic Interior Concept',
    description: 'A complete residential styling mockup focusing on custom Scandinavian hardwood, open-concept floorboards, and dynamic natural ambient lighting.',
    category: 'Interior',
    tags: 'Residential, Scandinavian Style, Oakwood, Minimal',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZ0hEE3hj43gqmaHbzzu4lzrjylhReToxNTm42UX5cuymVH52zD9KfWMcQcXyNjkCFfSraBe9PSJ85fqUX9Qmgxd_DuLhNx2mzNDgL0bk4nYyuQA7F0LUP11ibewZzSYb2dQXp4CxLT6xXxj_9ezX3z40c1sr-0ub7geTZCeeZU2W7Xse0ZiCVCiEZQ2eKKbSPNPCWzUqkZOM3pJx6bjKfniVI0YBTs1yz5h6DYYBxnzsxFwh_902-8mnPXwL-hMBimoVS-kCiVFs',
    views: 310,
    viewsGrowth: 0.0,
    modifiedAt: '2 weeks ago',
    createdAtDate: 'Dec 15, 2023',
    client: 'Residential',
    year: 2023,
    status: 'Draft',
    location: 'Oslo',
    featured: false
  },
  {
    id: 'proj-11',
    title: 'Cyber-City Visions',
    description: 'An futuristic visual exploration incorporating holographic structures, wet dark roads, volumetric atmosphere, and intense neon signages.',
    category: 'Visuals',
    tags: 'Visual Art, Cyberpunk, Concept, Neon',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHsXvNdx62x59VHZihyAmI5ppbX1aahVF3A-oMfRqN-_8BymdFMU6aVZyBIWqJvKU_vcDqQoL297hS54-rQEtA0MEXuijjNs-R4mdpM3-CnCbQuNowAqyJSqlqH5KX_gVZywW1sEFzZUT7XV4zrKuXDtNs2Eo2Fctv8QzoW6DhVSTeCN9KFeFYm7V9i9uUc0DhX9FAvAu4fyESznqXczx_lNU4wox1b0Up97f2lXvXYfFD4U4TZLzoSFMN2DsyARPF35FLS-xLIMI',
    views: 954,
    viewsGrowth: 11.2,
    modifiedAt: '3 weeks ago',
    createdAtDate: 'Jan 20, 2024',
    client: 'Visual Art',
    year: 2024,
    status: 'Published',
    location: 'Meta',
    featured: true
  }
];

// Seed initial traffic chart data
export const INITIAL_TRAFFIC_DATA = [
  { day: 'Mon', views: 120, pct: 30 },
  { day: 'Tue', views: 180, pct: 45 },
  { day: 'Wed', views: 160, pct: 40 },
  { day: 'Thu', views: 250, pct: 65 },
  { day: 'Fri', views: 320, pct: 85 },
  { day: 'Sat', views: 210, pct: 55 },
  { day: 'Sun', views: 380, pct: 95 }
];
